services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - user-service
      - job-service
      - proposal-service
      - contract-service

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env

  job-service:
    build: ./job-service
    ports:
      - "4002:4002"
    env_file:
      - ./job-service/.env

  proposal-service:
    build: ./proposal-service
    ports:
      - "4003:4003"
    env_file:
      - ./proposal-service/.env

  contract-service:
    build: ./contract-service
    ports:
      - "4004:4004"
    env_file:
      - ./contract-service/.env

  # payment-service:
  #   build: ./payment-service
  #   env_file:
  #     - ./payment-service/.env

  # notification-service:
  #   build: ./notification-service
  #   env_file:
  #     - ./notification-service/.env
